# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='team_one',
            field=models.CharField(default='Team A', max_length=25),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='team_two',
            field=models.CharField(default='Team B', max_length=25),
        ),
    ]
