# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0002_auto_20180720_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='team_one_image',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='team_two_image',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='tournament_name',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='team_one',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='team_two',
            field=models.CharField(max_length=25),
        ),
    ]
