# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0010_auto_20180729_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetails',
            name='match_date',
            field=models.DateTimeField(default=1532849834.4860954),
        ),
    ]
