# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0012_auto_20180729_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macth_name', models.CharField(max_length=100)),
                ('tournament_name', models.CharField(max_length=25)),
                ('match_date', models.DateTimeField()),
                ('match_url', models.CharField(max_length=25)),
                ('team_one', models.CharField(max_length=25)),
                ('team_two', models.CharField(max_length=25)),
                ('team_one_image', models.CharField(max_length=25)),
                ('team_two_image', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchDetails',
        ),
    ]
