# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0013_auto_20180729_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='match_tick',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
