# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0014_matchdetail_match_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetail',
            name='match_tick',
            field=models.IntegerField(blank=True),
        ),
    ]
