# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0015_auto_20180729_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdetail',
            old_name='macth_name',
            new_name='match_name',
        ),
    ]
