# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0016_auto_20180729_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaPakistanTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(default=0)),
                ('username_of_player', models.CharField(max_length=64)),
                ('match_name', models.CharField(max_length=100)),
                ('Rohit_Sharma', models.CharField(default="{'Player_Id':1, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Shikhar_Dhawan', models.CharField(default="{'Player_Id':2, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Virat_Kohli', models.CharField(default="{'Player_Id':3, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Dinesh_Karthik', models.CharField(default="{'Player_Id':4, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Suresh_Raina', models.CharField(default="{'Player_Id':5, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('MS_Dhoni', models.CharField(default="{'Player_Id':6, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Hardik_Pandya', models.CharField(default="{'Player_Id':7, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Bhuvneshwar_Kumar', models.CharField(default="{'Player_Id':8, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Kuldeep_Yadav', models.CharField(default="{'Player_Id':9, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Shardul_Thakur', models.CharField(default="{'Player_Id':10, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Yuzvendra_Chahal', models.CharField(default="{'Player_Id':11, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Shreyas_Iyer', models.CharField(default="{'Player_Id':12, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Axar_Patel', models.CharField(default="{'Player_Id':13, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Siddarth_Kaul', models.CharField(default="{'Player_Id':14, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Lokesh_Rahul', models.CharField(default="{'Player_Id':15, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
                ('Umesh_Yadav', models.CharField(default="{'Player_Id':16, 'Team':'India', 'Captain:'False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0,}", max_length=255)),
            ],
        ),
    ]
