# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0017_indiapakistanteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Axar_Patel',
            field=models.CharField(default="{'Player_Id':13, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Bhuvneshwar_Kumar',
            field=models.CharField(default="{'Player_Id':8, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Dinesh_Karthik',
            field=models.CharField(default="{'Player_Id':4, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Hardik_Pandya',
            field=models.CharField(default="{'Player_Id':7, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Kuldeep_Yadav',
            field=models.CharField(default="{'Player_Id':9, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Lokesh_Rahul',
            field=models.CharField(default="{'Player_Id':15, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='MS_Dhoni',
            field=models.CharField(default="{'Player_Id':6, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Rohit_Sharma',
            field=models.CharField(default="{'Player_Id':1, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Shardul_Thakur',
            field=models.CharField(default="{'Player_Id':10, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Shikhar_Dhawan',
            field=models.CharField(default="{'Player_Id':2, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Shreyas_Iyer',
            field=models.CharField(default="{'Player_Id':12, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Siddarth_Kaul',
            field=models.CharField(default="{'Player_Id':14, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Suresh_Raina',
            field=models.CharField(default="{'Player_Id':5, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Umesh_Yadav',
            field=models.CharField(default="{'Player_Id':16, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Virat_Kohli',
            field=models.CharField(default="{'Player_Id':3, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Yuzvendra_Chahal',
            field=models.CharField(default="{'Player_Id':11, 'Team':'India', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
    ]
