# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0018_auto_20180801_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Axar_Patel',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Bhuvneshwar_Kumar',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Dinesh_Karthik',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Hardik_Pandya',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Kuldeep_Yadav',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Lokesh_Rahul',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='MS_Dhoni',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Rohit_Sharma',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Shardul_Thakur',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Shikhar_Dhawan',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Shreyas_Iyer',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Siddarth_Kaul',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Suresh_Raina',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Umesh_Yadav',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Virat_Kohli',
        ),
        migrations.RemoveField(
            model_name='indiapakistanteam',
            name='Yuzvendra_Chahal',
        ),
        migrations.AddField(
            model_name='indiapakistanteam',
            name='Keeper',
            field=models.CharField(default="{'Player_Id':0, 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
    ]
