# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0019_auto_20180805_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indiapakistanteam',
            old_name='match_name',
            new_name='match_slug',
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='team_no',
            field=models.IntegerField(default=1),
        ),
    ]
