# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0021_auto_20180807_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiapakistanteam',
            name='Bat6',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AddField(
            model_name='indiapakistanteam',
            name='Bat7',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AddField(
            model_name='indiapakistanteam',
            name='Bat8',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
    ]
