# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0023_auto_20180807_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinesh_Ramdin', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('MS_Dhoni', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Dinesh_Kartik', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Rohit_Sharma', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Shikhar_Dhawan', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Virat_Kohli', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Suresh_Raina', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Andre_Fletcher', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Evin_Lewis', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Marlon_Samuels', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Chadwick_Walton', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Shreyas_Iyer', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Lokesh_Rahul', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Hardik_Pandya', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Axar_Patel', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Andre_Russell', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Rovman_Powell', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Carlos_Brathwaite', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Bhuvneshwar_Kumar', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Kuldeep_Yadav', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Shardul_Thakur', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Yuzvendra_Chahal', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Siddarth_Kaul', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Umesh_Yadav', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Ashley_Nurse', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Samuel_Badree', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Kesrick_Williams', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Keemo_Paul', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
                ('Sheldon_Cottrell', models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Keeper',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player10',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player11',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player2',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player3',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player4',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player5',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player6',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player7',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player8',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player9',
            field=models.CharField(default="{'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
    ]
