# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0024_auto_20180813_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Keeper',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player10',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player11',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player2',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player3',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player4',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player5',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player6',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player7',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player8',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
        migrations.AlterField(
            model_name='indiapakistanteam',
            name='Player9',
            field=models.CharField(default="{'Player':'Anon', 'Team':'', 'Captain':False, 'Vice_Captain':False, 'Current_Points':0, 'Total_Points':0}", max_length=255),
        ),
    ]
