# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0025_auto_20180813_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdetail',
            old_name='match_url',
            new_name='match_slug',
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='match_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='match_slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
