# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0026_auto_20180813_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdetail',
            old_name='match_name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Andre_Fletcher',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Andre_Russell',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Ashley_Nurse',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Axar_Patel',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Bhuvneshwar_Kumar',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Carlos_Brathwaite',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Chadwick_Walton',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Dinesh_Kartik',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Dinesh_Ramdin',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Evin_Lewis',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Hardik_Pandya',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Keemo_Paul',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Kesrick_Williams',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Kuldeep_Yadav',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Lokesh_Rahul',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='MS_Dhoni',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Marlon_Samuels',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Rohit_Sharma',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Rovman_Powell',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Samuel_Badree',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Shardul_Thakur',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Sheldon_Cottrell',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Shikhar_Dhawan',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Shreyas_Iyer',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Siddarth_Kaul',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Suresh_Raina',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Umesh_Yadav',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Virat_Kohli',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='Yuzvendra_Chahal',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='match_slug',
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player_credit_points',
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player_current_team',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player_type',
            field=models.CharField(default='Keeper/Batsman/Allrounder/Bowler', max_length=25),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
