# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0028_auto_20180814_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetail',
            name='player_credit_points',
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=3),
        ),
    ]
