# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0031_auto_20180816_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_slug', models.CharField(max_length=512)),
                ('contest_price', models.IntegerField()),
                ('contest_fee', models.IntegerField()),
                ('contest_size', models.IntegerField()),
                ('total_player_joined', models.IntegerField()),
                ('contest_category', models.CharField(max_length=100)),
                ('contest_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_center.MatchDetail')),
            ],
        ),
    ]
