# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0032_contestdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestdetail',
            name='filled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchdetail',
            name='match_slug',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
