# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0034_contestdetail_joined_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestdetail',
            name='contest_slug',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
