# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0035_auto_20180901_0225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndiaPakistanTeam',
            new_name='IndiaWestIndiesTeam',
        ),
        migrations.AlterField(
            model_name='contestdetail',
            name='contest_slug',
            field=models.CharField(default='Test', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='matchdetail',
            name='match_slug',
            field=models.CharField(default='Test', max_length=25, unique=True),
        ),
    ]
