# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0036_auto_20180901_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_user', models.CharField(max_length=255)),
                ('joined_contest', models.CharField(max_length=255)),
                ('joined_user_team', models.CharField(max_length=255)),
            ],
        ),
    ]
