# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0039_auto_20180903_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestdetail',
            name='bonus_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestdetail',
            name='free_contest',
            field=models.BooleanField(default=False),
        ),
    ]
