# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180515_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Username', message='Username only contain A-Z,a-z,0-9 or . _ + - $', regex='^[a-zA-Z0-9.+-_]*$')]),
        ),
    ]
