# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
